markdown: kramdown
highlighter: rouge

timezone: Europe/Madrid

name: We Are Random [WAR]
description: This is a Jekyll testing page

url: https://wearerandom.github.io

exclude:
  - README.md
  - .gitignore
